services:
  app:
    image: nivekrish/django-ecommerce:latest
    networks:
      - web
   
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - C:/Users/cosai/.docker/Nivetha/ecommerce/:/usr/share/nginx/ecommerce/ 
      - C:/Users/cosai/.docker/Nivetha/static/:/usr/share/nginx/static/
      
    depends_on:
      - app
    networks:
      - web

networks:
  web:
