services:
  app:
    image: django-ecommerce
    networks:
      - web

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - web

networks:
  web:
