services:
  app:
    image: nivekrish/django-ecommerce:latest
    networks:
      - web
   
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static:ro
      - ./static/images:/app/static/images:ro
      
    depends_on:
      - app
    networks:
      - web

networks:
  web:
