services:
  app:
    image: nivekrish/django-ecommerce:latest
    networks:
      - web

  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./Nivetha:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - web

networks:
  web:
